set(SOURCE_FILES
    annotations_test.cpp
    box_test.cpp
    config_test.cpp
    data_types_test.cpp
    layout_test.cpp
    scatter_gl_test.cpp
    scatter_test.cpp
    subplots_test.cpp
    test_main.cpp
    violin_test.cpp
)
