set(SOURCE_FILES
    animations_test.cpp
    annotations_test.cpp
    bar_test.cpp
    box_test.cpp
    color_scales.cpp
    config_test.cpp
    data_types_test.cpp
    heatmap_test.cpp
    histogram_test.cpp
    layout_test.cpp
    scatter_gl_test.cpp
    scatter_test.cpp
    subplots_test.cpp
    test_main.cpp
    violin_test.cpp
)
