image: ubuntu:focal

stages:
  - test
  - deploy
  - release

variables:
  LOWER_PROJECT_NAME: "plotly_plotter"
  UPPER_PROJECT_NAME: "PLOTLY_PLOTTER"
  SECURE_LOG_LEVEL: debug

line count:
  stage: test
  needs: []
  image: registry.gitlab.com/musicscience37projects/docker/scc-docker
  script:
    - mkdir -p line_count
    - scc
      --format-multi "tabular:stdout,html:line_count/line_count.html"
      .
    - scc
      --format-multi "openmetrics:line_count/cpp_line_count.txt"
      -i h,cpp
      .
    - scc
      --format-multi "tabular:stdout,html:line_count/src_line_count.html"
      --by-file -s complexity
      include src
  artifacts:
    paths:
      - line_count
    reports:
      metrics:
        - "line_count/cpp_line_count.txt"
    expire_in: "1 mos"
  interruptible: true

pre-commit:
  stage: test
  needs: []
  image: musicscience37/clang-ci:clang19
  variables:
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry install
    - poetry run pre-commit run --all-files
  cache:
    - key:
        prefix: poetry-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
  interruptible: true

spell check:
  stage: test
  needs: []
  image: node
  script:
    - npm install -g cspell
    - cspell lint
      "**/*.h"
      "**/*.cpp"
      "**/*.py"
      "**/*.cmake"
      "**/*.txt"
      "**/*.md"
      "**/*.rst"
      "**/*.puml"
      "**/*.bib"
      "**/*.yaml"
      "**/*.yml"
      "**/*.json"
      "**/*.toml"
      "**/*.sh"
      "**/*.bash"
  interruptible: true

test release:
  stage: test
  needs: []
  parallel:
    matrix:
      - COMPILER_TYPE: "gcc12"
        IMAGE_PATH: "musicscience37/gcc-ci"
      - COMPILER_TYPE: "clang19"
        IMAGE_PATH: "musicscience37/clang-ci"
  image: ${IMAGE_PATH}:${COMPILER_TYPE}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    BUILD_TYPE: Release
    BUILD_DIR: build_${COMPILER_TYPE}_release
    CCACHE_DIR: ${CI_PROJECT_DIR}/.ccache
    CCACHE_COMPILERCHECK: content
    CCACHE_MAXSIZE: 1G
    VCPKG_DEFAULT_BINARY_CACHE: ${CI_PROJECT_DIR}/.vcpkg-cache
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
    PLAYWRIGHT_BROWSERS_PATH: ${CI_PROJECT_DIR}/.playwright
  before_script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry install
    - ./vcpkg/bootstrap-vcpkg.sh
    - mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
    - apt-get update
    - apt-get install -y gpg
    - curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/chrome-keyring.gpg
    - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install -y google-chrome-stable
    - poetry run playwright install chromium
    - mkdir $BUILD_DIR
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_UNIT_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_INTEG_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_BENCH=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - cmake --build .
    - ctest -V
  cache:
    - key:
        prefix: poetry-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
    - key:
        prefix: vcpkg-${CI_JOB_NAME}
        files:
          - vcpkg-configuration.json
      paths:
        - .vcpkg-cache
    - key: ccache-${CI_JOB_NAME}
      paths:
        - .ccache
    - key:
        prefix: playwright-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .playwright
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - "*.html"
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"
  interruptible: true

test debug:
  extends: test release
  parallel:
    matrix:
      - COMPILER_TYPE: "gcc12"
        IMAGE_PATH: "musicscience37/gcc-ci"
      - COMPILER_TYPE: "clang19"
        IMAGE_PATH: "musicscience37/clang-ci"
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_${COMPILER_TYPE}_debug
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_UNIT_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_INTEG_TESTS=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_BENCH=OFF
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - cmake --build .
    - ctest -V

static analysis:
  extends: test release
  parallel:
    matrix:
      - COMPILER_TYPE: "clang19"
        IMAGE_PATH: "musicscience37/clang-ci"
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_static_analysis
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DVCPKG_TARGET_TRIPLET=x64-linux-llvm
      -DVCPKG_HOST_TRIPLET=x64-linux-llvm
      -DCMAKE_CXX_FLAGS=-stdlib=libc++
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_BENCH=ON
      -D${UPPER_PROJECT_NAME}_BUILD_EXAMPLES=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CPP_WARNINGS:BOOL=ON
    - cd ..
    - poetry run clang-tidy-checker -b ${BUILD_DIR}

clang coverage:
  extends: test release
  parallel:
    matrix:
      - COMPILER_TYPE: "clang19"
        IMAGE_PATH: "musicscience37/clang-ci"
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_clang_coverage
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DVCPKG_TARGET_TRIPLET=x64-linux-llvm
      -DVCPKG_HOST_TRIPLET=x64-linux-llvm
      -DCMAKE_BUILD_TYPE=Debug
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=-stdlib=libc++ -fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_C_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage
    - poetry run lcov_cobertura $BUILD_DIR/coverage/coverage --output $BUILD_DIR/coverage.xml
  coverage: '/[^\s]+%\s+\d+\s+\d+\s+\s[^\s]+%/'
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - $BUILD_DIR/coverage
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
      coverage_report:
        coverage_format: cobertura
        path: $BUILD_DIR/coverage.xml
    when: always
    expire_in: "1 mos"

test asan ubsan:
  extends: test release
  parallel:
    matrix:
      - COMPILER_TYPE: "clang19"
        IMAGE_PATH: "musicscience37/clang-ci"
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_clang_asan_ubsan
    ASAN_OPTIONS: "alloc_dealloc_mismatch=0"
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DVCPKG_TARGET_TRIPLET=x64-linux-llvm
      -DVCPKG_HOST_TRIPLET=x64-linux-llvm
      -DCMAKE_CXX_FLAGS=-stdlib=libc++
      -DCMAKE_BUILD_TYPE=Debug
      -D${UPPER_PROJECT_NAME}_TESTING:BOOL=ON
      -D${UPPER_PROJECT_NAME}_WRITE_JUNIT:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_AUSAN:BOOL=ON
      -D${UPPER_PROJECT_NAME}_ENABLE_CCACHE:BOOL=ON
    - cmake --build .
    - ctest -V

msvc-release:
  tags:
    - saas-windows-medium-amd64
  stage: test
  needs: []
  dependencies: []
  variables:
    BUILD_DIR: build_msvc
    GIT_SUBMODULE_STRATEGY: recursive
    # workaround in https://github.com/python-poetry/poetry/issues/1917#issuecomment-1235998997
    PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
    PLAYWRIGHT_BROWSERS_PATH: ${CI_PROJECT_DIR}/.playwright
    VCPKG_DEFAULT_BINARY_CACHE: ${CI_PROJECT_DIR}/.vcpkg-cache
    CCACHE_DIR: ${CI_PROJECT_DIR}/.ccache
    CCACHE_COMPILERCHECK: content
    CCACHE_MAXSIZE: 1G
  before_script:
    - New-Item -ItemType Directory -Force -Path $VCPKG_DEFAULT_BINARY_CACHE
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
    - choco install python313 -y
    - choco install ccache -y
    - RefreshEnv
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry sync --only test
    - poetry run playwright install chromium
    - .\vcpkg\bootstrap-vcpkg.bat
    - mkdir $BUILD_DIR
  script:
    - cd $BUILD_DIR
    - cmd.exe /C ..\scripts\ci_win.cmd
  cache:
    - key:
        prefix: poetry-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
    - key:
        prefix: vcpkg-${CI_JOB_NAME}
        files:
          - vcpkg-configuration.json
      paths:
        - .vcpkg-cache
    - key: ccache-${CI_JOB_NAME}
      paths:
        - .ccache
    - key:
        prefix: playwright-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .playwright
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - "*.html"
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"
  interruptible: true

doc:
  extends: test release
  parallel:
    matrix:
      - COMPILER_TYPE: "clang19"
        IMAGE_PATH: "musicscience37/sphinx-doxygen"
  variables:
    BUILD_TYPE: Release
    BUILD_DIR: build_doc
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -D${UPPER_PROJECT_NAME}_BUILD_DOC:BOOL=ON
    - cmake --build . --target ${LOWER_PROJECT_NAME}_doc
  cache:
    - key:
        prefix: poetry-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
    - key:
        prefix: vcpkg-${CI_JOB_NAME}
        files:
          - vcpkg-configuration.json
      paths:
        - .vcpkg-cache
    - key: ccache-${CI_JOB_NAME}
      paths:
        - .ccache
    - key:
        prefix: jupyter-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - doc/sphinx/build/jupyter_cache
  artifacts:
    paths:
      - build_doc/doc/html
    when: always
    expire_in: "1 mos"
  interruptible: true

pages:
  stage: deploy
  only:
    - main
  needs:
    - doc
    - clang coverage
    - line count
  dependencies:
    - doc
    - clang coverage
    - line count
  image: alpine
  script:
    - rm -rf public
    - mv build_doc/doc/html public
    - mv build_clang_coverage/coverage/html public/coverage
    - mv line_count public/line_count
  artifacts:
    paths:
      - public

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
  script:
    - echo "This is a release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: "$CI_COMMIT_TAG"
    description: "./doc/sphinx/src/change_log/${CI_COMMIT_TAG}.md"
