set(SOURCE_FILES
    array_view_test.cpp
    details/escape_for_html_test.cpp
    details/file_handle_test.cpp
    details/html_to_pdf_test.cpp
    figure_test.cpp
    json_converter_test.cpp
    json_document_test.cpp
    json_value_test.cpp
    layout_test.cpp
    test_main.cpp
    traces/box_test.cpp
    traces/scatter_test.cpp
    traces/violin_test.cpp
    write_html_test.cpp
)
