set(SOURCE_FILES
    array_view_test.cpp
    config_test.cpp
    data_column_test.cpp
    data_table_test.cpp
    details/escape_for_html_test.cpp
    details/file_handle_test.cpp
    figure_builders/figure_builder_base_test.cpp
    figure_builders/line_test.cpp
    figure_builders/scatter_test.cpp
    figure_test.cpp
    json_converter_test.cpp
    json_document_test.cpp
    json_value_test.cpp
    layout_test.cpp
    test_main.cpp
    to_string_test.cpp
    traces/box_test.cpp
    traces/scatter_test.cpp
    traces/violin_test.cpp
    write_html_test.cpp
)
