set(SOURCE_FILES
    plotly_plotter/color_scales.cpp
    plotly_plotter/details/format_time.cpp
    plotly_plotter/details/write_html_impl.cpp
    plotly_plotter/figure_builders/bar.cpp
    plotly_plotter/figure_builders/box.cpp
    plotly_plotter/figure_builders/details/figure_builder_helper.cpp
    plotly_plotter/figure_builders/figure_builder_base.cpp
    plotly_plotter/figure_builders/histogram.cpp
    plotly_plotter/figure_builders/scatter.cpp
    plotly_plotter/figure_builders/violin.cpp
    plotly_plotter/invert_color_scale.cpp
    plotly_plotter/io/chrome_converter.cpp
    plotly_plotter/io/details/execute_command.cpp
    plotly_plotter/io/html_to_pdf_converter_base.cpp
    plotly_plotter/io/html_to_png_converter_base.cpp
    plotly_plotter/io/pdf_to_svg_converter_base.cpp
    plotly_plotter/io/pdftocairo_converter.cpp
    plotly_plotter/io/playwright_converter.cpp
    plotly_plotter/json_converter.cpp
    plotly_plotter/styles.cpp
    plotly_plotter/to_string.cpp
    plotly_plotter/utils/calculate_histogram_bin_width.cpp
    plotly_plotter/write_pdf.cpp
    plotly_plotter/write_png.cpp
    plotly_plotter/write_svg.cpp
)
